labels = ['Online Library Resources Query',
 'Walden University Career Placement Services For Communication Graduates Query',
 'Program Completion Time Query',
 'Program Inquiry Coordinator',
 'Communication Professional Organizations Recommendations',
 'Communication Field Challenges',
 'Career Advancement Certifications In Communication',
 'Online Program Campus Requirements Query',
 'Walden University Online Learning Overview',
 'Tuition Adjustment Policy',
 'Career Opportunities After B S Communication',
 'Walden University Degree Completion Time',
 'Online Student Support In B S Communication_ Walden University',
 'Financial Aid Options For B S Communication Students',
 'Emerging Communication Trends',
 'Communication Program Specializations Query',
 'Online Research Resources For Communication Students',
 'Digital Marketing Opportunities From Communication Degree',
 'Lifelong  Learning  Strategies in  Communication',
 'Media  Ethics and  Responsibility',
 'Career Communication Advice',
 'Student Financial Aid Options',
 'Communication Career Salary Ranges',
 'Walden University Career Services',
 'Online Education Availability Query',
 'Online Student Engagement Strategies At Walden University',
 'Communication Skills Development',
 'Tuition Policy Inquiry',
 'Tuition Reductions Scope Query',
 'Strategic  Communication for  Non- Profit  Advancement',
 'Communication  Specialization  Paths',
 'Walden University Career Placement Services For Communication Graduates Query',
 'Disability Support Services At Walden University',
 'Online Student Engagement Strategies At Walden University',
 'Walden University B S Communication Application Process',
 'Education Program Requirements',
 'Student Support Services Overview',
 'Financial Aid Inquiry',
 'Online Communication Program Orientation',
 'University Student To Faculty Ratio Query',
 'Online Student Technology Requirements',
 'Communication Career Paths Options',
 'Communication Career Advantages',
 'Public Service Career Opportunities',
 'Tuition Reduction Termination Conditions',
 'Online Class Scheduling System',
 'Communication Graduate Skills Employers Seek',
 'Practical Experience Opportunities Checker',
 'Financial Aid Eligibility Checker',
 'Walden University Degree Programs',
 'Networking Significance In Communication',
 'Credit Transfer Inquiry',
 'Online B S Communication Technical Requirements',
 'Portfolio Development In Communication',
 'Issue Resolution Process',
 'Educational Quality Assurance',
 'Work Study Balance At Walden University',
 'Online Student Orientation Query',
 'Walden University Application Process']